<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class CandidatesSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $allCandidates = [
            [
                'name' => 'Alice Gabriely',
                'age' => 30,
                'city' => 'Dobrada/SP',
                'bestSinger' => 'Maiara & Maraisa',
                'weight' => '170',
                'profession' => 'Técnica de Enfermagem',
                'sex' => 'F',
                'description' => ' Agregaria no sentido de entender que pode superar seus limites e provar a si mesma o quanto é capaz de enfrentar obstáculos para realizar todos os seus sonhos.',
                'votes' => 0,
            ],
            [
                'name' => 'Anna Wichester',
                'age' => 21,
                'city' => 'Pedregulho/SP',
                'bestSinger' => 'Edson & Hudson',
                'weight' => '176',
                'profession' => 'Maquiadora',
                'sex' => 'F',
                'description' => 'Acredito que, como Miss, posso inspirar outras pessoas a irem atrás dos seus sonhos, de se espelharem com os ideais que carrego, ser referência para as meninas que sonham em ter uma faixa e encoraja-las a seguir seus sonhos se isso for, além de promover a importância de preservar nossa herança cultural que vem se perdendo aos poucos com o passar do tempo, quero ser um elo entre as tradições do passado e as oportunidades do futuro, mostrando a todos a verdadeira essência do espírito do rodeio brasileiro. Meu desejo de ser Miss Rodeio Brasil 2024 não é apenas um sonho pessoal, mas sim um compromisso profundo com tudo que esse título significa, estou pronta para representar com honra, humildade e dedicação, e espero ter a chance de compartilhar minha paixão e ideais com todos que também amam esse universo.',
                'votes' => 0,
            ],
            [
                'name' => 'Barbara Fernandes',
                'age' => 29,
                'city' => 'Ribeirão Preto/SP',
                'bestSinger' => 'Jorge & Matheus',
                'weight' => '163',
                'profession' => 'Fisioterapeuta',
                'sex' => 'F',
                'description' => 'Ser Miss Rodeio vai muito além da beleza física e eu quero ter essa grande oportunidade de estar representando a minha cidade, Ribeirão Preto. De poder levar o meu carisma, a minha simpatia e a humildade por todos os rodeios, inclusive no maior rodeio da América Latina.',
                'votes' => 0,
            ],
            [
                'name' => 'Bruno Furman',
                'age' => 28,
                'city' => 'Contenda/PR',
                'bestSinger' => 'João Carreiro',
                'weight' => '181',
                'profession' => 'Vendedor',
                'sex' => 'M',
                'description' => 'Pensando bem, nunca quis ou tenha pensado nisso. Ser Mister Rodeio leva uma autoridade e responsabilidade de representar uma classe que já é muito bem representada, pelo povo sertanejo, na música, no trabalho, na tradição que ser sertanejo carrega. Ser Mister é chegar ao ápice de uma categoria na qual muitos se dedicaram para chegar e apenas um será merecedor. Penso que ser Mister Rodeio Brasil será uma honra que eu farei com que reconheçam a grandiosidade do rodeio brasileiro, que exporta grandes peões para o mundo do rodeio. Querer até quero, mas se mereço outros que vão decidir.',
                'votes' => 0,
            ],
            [
                'name' => 'Daniela Mendonça',
                'age' => 26,
                'city' => 'Brazópolis/MG',
                'bestSinger' => 'João Bosco & Vinícius',
                'weight' => '168',
                'profession' => 'Gerente',
                'sex' => 'F',
                'description' => 'Por amor ao Rodeio, por estar sempre participando, não só dos desfiles, mas do rodeio em si. E tenho absoluta certeza que eu iria representar bem o significado desta faixa no mundo country!',
                'votes' => 0,
            ],
            [
                'name' => 'Emillyn Millian',
                'age' => 28,
                'city' => 'Ribeirão Preto/SP',
                'bestSinger' => 'US Agroboys',
                'weight' => '160',
                'profession' => 'Autônoma',
                'sex' => 'F',
                'description' => 'Além de aumentar a minha própria autoestima eu também gostaria de influenciar outras mulheres a se aceitarem como são, elevando a confiança e  mostrando que somos capazes de se encaixar em qualquer coisa que sonharmos fazer.',
                'votes' => 0,
            ],
            [
                'name' => 'Esttevan',
                'age' => 26,
                'city' => 'São Lourenço da Serra/SP',
                'bestSinger' => 'Jorge & Matheus',
                'weight' => '189',
                'profession' => 'Artista',
                'sex' => 'M',
                'description' => 'Como artista me descobri como cantor, creio que por crescer no instruir sempre tive uma vida sertaneja e repleta de coisas boas e leves da natureza. Quero trazer essas boas lembranças e incentivar crianças jovens e adultos a seguir o sonho do seu coração.',
                'votes' => 0,
            ],
            [
                'name' => 'Julia Camylle',
                'age' => 21,
                'city' => 'Barretos/SP',
                'bestSinger' => 'Chitãozinho & Xororó',
                'weight' => '170',
                'profession' => 'Perita Criminal',
                'sex' => 'F',
                'description' => 'Pela representação cultural e estadual e suas características, defesa de direitos da agropecuária e das indústrias no Brasil. Além de projeto sociais para ajuda humanitária, e reconhecimento ao título, e seus ideais.',
                'votes' => 0,
            ],
            [
                'name' => 'Julia Reginato',
                'age' => 23,
                'city' => 'Pitangueiras/SP',
                'bestSinger' => 'Chitãozinho & Xororó',
                'weight' => '171',
                'profession' => 'Vendedora',
                'sex' => 'F',
                'description' => 'Ser a Miss Rodeio Brasil, para mim, representa muito mais do que ganhar um concurso. Talvez pareça clichê, mas se trata de um dos maiores sonhos da minha vida. Esperei por anos, me preparei e me dediquei a vida toda para esse momento.',
                'votes' => 0,
            ],
            [
                'name' => 'Junior Consolini',
                'age' => 28,
                'city' => 'São José do Rio Pardo/SP',
                'bestSinger' => 'Jorge & Matheus',
                'weight' => '172',
                'profession' => 'Body Piercer',
                'sex' => 'M',
                'description' => 'Por ser neto de administrador de grande fazenda, sempre tive contato com esse meio. Receber esse título me leva uma infância raiz e feliz que eu tinha, além claro das oportunidades que virão e com esse título sei também que virão muitas responsabilidades. Honrarei muito esse título!',
                'votes' => 0,
            ],
            [
                'name' => 'Kadu Deangelo',
                'age' => 39,
                'city' => 'Barretos/SP',
                'bestSinger' => 'Zé Neto & Cristiano',
                'weight' => '183',
                'profession' => 'Personal Trainer',
                'sex' => 'M',
                'description' => 'Por ter nascido e criado praticamente nesse meio e também por ter nascido na cidade que mais diz respeito a “vida sertaneja”.',
                'votes' => 0,
            ],
            [
                'name' => 'Laiana Caroline',
                'age' => 22,
                'city' => 'Conceição das Pedras/MG',
                'bestSinger' => 'Ana Castela',
                'weight' => '170',
                'profession' => 'Dançarina, coreógrafa, modelo e maquiadora.',
                'sex' => 'F',
                'description' => 'Primeiramente, ser Miss é o sentido de vida para mim, subir em uma passarela é saber que eu tenho um motivo para viver, amando e vivendo cada momento para seguir em frente. Com isso, quero ser a Miss Rodeio Brasil 2024 para honrar toda minha história no mundo Miss e ser a representatividade da mulher nesse meio sertanejo e country das passarelas, encorajando outras a seguir o mesmo caminho.',
                'votes' => 0,
            ],
            [
                'name' => 'Lavinia Narcizo',
                'age' => 23,
                'city' => 'Pitangueiras/SP',
                'bestSinger' => 'Paula Fernandes',
                'weight' => '160',
                'profession' => 'Esteticista, Cosmetóloga e Digital Influencer',
                'sex' => 'F',
                'description' => 'Por amar e por crescer imersa na cultura sertaneja, para poder representar as mulheres de nosso Brasil, que pode ser jovem ou adulta, profissional, dona de casa, mãe, esposa, o que ela quiser e estar apta. Essa e tantas outras sou eu, e por isso quero ser a Miss Rodeio Brasil 2024.',
                'votes' => 0,
            ],
            [
                'name' => 'Livia Venezian',
                'age' => 21,
                'city' => 'São José do Rio Pardo/SP',
                'bestSinger' => 'Jorge e Matheus',
                'weight' => '161',
                'profession' => 'Empresária, estudante de Fisioterapia e Educação Física',
                'sex' => 'F',
                'description' => 'Gostaria de trazer este título para São José Do Rio Pardo! Pois é meu sonho desde muito pequena me ver representado.',
                'votes' => 0,
            ],
            [
                'name' => 'Luis Felipe Lopes',
                'age' => 29,
                'city' => 'Três Lagoas/MS',
                'bestSinger' => 'Chico Rey & Paraná',
                'weight' => '187',
                'profession' => 'Engenheiro Civil',
                'sex' => 'M',
                'description' => 'Porque acredito que tenho o perfil do concurso, sou apaixonado por esse mundo da tradição sertaneja e seria um prazer enorme representá-lo.',
                'votes' => 0,
            ],
            [
                'name' => 'Marcela Ribeiro',
                'age' => 24,
                'city' => 'Pirangi/SP',
                'bestSinger' => 'Luan Santana',
                'weight' => '154',
                'profession' => 'Estudante de Pedagogia',
                'sex' => 'F',
                'description' => 'Ser miss vai muito além da beleza física, do carisma, simpatia e humildade. Ser Miss vai muito além de um título e sim poder mostrar a nossa paixão pelo nosso rodeio e seria uma honra poder ser a Miss Rodeio Brasil  já que sou apaixonada pelo rodeio.',
                'votes' => 0,   
            ],
            [
                'name' => 'Marcela Vitoria',
                'age' => 20,
                'city' => 'Salto de Pirapora/SP',
                'bestSinger' => 'Ana Castela',
                'weight' => '175',
                'profession' => 'Modelo e vendedora de loja de cosmético',
                'sex' => 'F',
                'description' => 'Para realizar um sonho, o qual era ser a rainha do rodeio de Barretos como eu não poderia participar por não ser moradora de Barretos então decidi participar do concurso Miss Rodeio Brasil onde será em Barretos e a ganhadora participará da festa de rodeio de Barretos e ainda estarei fazendo o que eu amo que  é desfilar em passarela e estar no mundo country.',
                'votes' => 0,
            ],
            [
                'name' => 'Marco Silva',
                'age' => 32,
                'city' => 'Frutal/MG',
                'bestSinger' => 'Icaro & Gilmar',
                'weight' => '181',
                'profession' => 'Agente Comunitário de Saúde',
                'sex' => 'M',
                'description' => 'Quero ser Mister porque de onde venho a cultura do rodeio é muito intensa, e quero ser um representante da Minha Cidade, e sempre foi um grande sonho em poder fazer parte desse ciclo maravilhoso, que sempre traz a beleza country. E servir de inspiração à aqueles que também sonham com esse título.',
                'votes' => 0,
            ],
            [
                'name' => 'Maria Edhuarda',
                'age' => 20,
                'city' => 'Lapa/PR',
                'bestSinger' => 'Léo & Raphael',
                'weight' => '169',
                'profession' => 'Monitora escolar',
                'sex' => 'F',
                'description' => 'Vejamos bem, quero ser Miss, pois amo a vida do interior, vivo e convivo todos os dias com isso, a cultura e tradição que representa o trabalho duro e a luta de gerações, levado para as arenas, com os touros, cavalos, cowboys e cowgirls, ser parte deste meio, seria uma honra representar tudo isso!',
                'votes' => 0,
            ],
            [
                'name' => 'Robson Copeski',
                'age' => 28,
                'city' => 'Serrana/SP',
                'bestSinger' => 'Maríilia Mendonça',
                'weight' => '182',
                'profession' => 'Estoquista',
                'sex' => 'M',
                'description' => 'Tornar-me o Mister Rodeio Brasil é o sonho que estou construindo há 10 anos, Representar a minha cidade em um concurso tão amplo e inclusivo como esse, nos faz querer sonhar. Sonhar que posso utilizar esse titulo para o bem. O titulo me possibilitaria alavancar minhas ações sociais incentivando pessoas a importância de ajudar ao próximo. Ser Mister é se tornar além de corpo, ser Mister é ter a consciência de que podemos construir um futuro melhor.',
                'votes' => 0,
            ],
            [
                'name' => 'Tata Mineira',
                'age' => 28,
                'city' => 'Quatro Barras/PR',
                'bestSinger' => 'Milionário & José Rico',
                'weight' => '168',
                'profession' => 'Caminhoneira Carreteira',
                'sex' => 'F',
                'description' => 'Porque ser miss vai muito além da beleza física, envolve carisma simpatia e humildade e dessa forma eu consigo incentivar as pessoas a acreditar em si mesmas e mostrar para as mulheres que nós estamos cada vez mais, alcançando o nosso espaço e que temos vez e vós em todos os campos que quisermos conquistar na vida.',
                'votes' => 0,
            ],
            [
                'name' => 'Thauanna Oliveira',
                'age' => 22,
                'city' => 'Campo Belo/MG',
                'bestSinger' => 'Ana Castela',
                'weight' => '168',
                'profession' => 'Atendente',
                'sex' => 'F',
                'description' => 'Sempre quis participar de um concurso de rodeio, meu sonho e participar e poder demonstrar a paixão que tenho pelo sertanejo, tá mais no meio de pessoas q gostam também desta maneira de vida.',
                'votes' => 0,
            ],
            [
                'name' => 'Ze Maria',
                'age' => 39,
                'city' => 'Palmares Paulista/SP',
                'bestSinger' => 'Gusttavo Lima',
                'weight' => '176',
                'profession' => 'Motorista',
                'sex' => 'M',
                'description' => 'Quando eu vim para o estado de São Paulo e me estabeleci aqui no interior, me apaixonei pelas festas de rodeio, sua alegria, sua energia,cultura e religiosidade, o que não difere da minha essência baiana. Quero mostrar que um negro nordestino pode sim ser o representante da cultura sertaneja deste país aliado ao tempero que todo bom baiano tem. Axé!',
                'votes' => 0,
            ],
        ];

        foreach ($allCandidates as $candidate) {
            $candidatesData = [
                'slug' => \Illuminate\Support\Str::slug($candidate['name']),
                'name' => $candidate['name'],
                'age' => $candidate['age'],
                'city' => $candidate['city'],
                'bestSinger' => $candidate['bestSinger'],
                'weight' => $candidate['weight'],
                'profession' => $candidate['profession'],
                'sex' => $candidate['sex'],
                'description' => $candidate['description'],
                'votes' => $candidate['votes'],
            ];

            \App\Models\Candidates::create($candidatesData);
        }
    }
}
